### ISSUE TITLE
Student może ventować

### ISSUE THREAD

**Issue by SGGWAmongUs** [wzimongus/wzimongus#112]
![image](https://github.com/wzimongus/wzimongus/assets/149107548/2d20993b-7019-408a-b9e7-262d16e016b4)
Po wciśnięciu "V":
![image](https://github.com/wzimongus/wzimongus/assets/149107548/448eff77-4091-4311-90cf-12b261de206f)

**Comment by qsqus** [comment]
to nie błąd, tylko w tamtym vencie jest włączone ventowanie studentów ;)
