### ISSUE TITLE
main : problem z kamerami i ventem

### ISSUE THREAD

**Issue by qsqus** [wzimongus/wzimongus#121]
gdy jest się obok kamer i vent, tak żeby można było użyć obu, to po otwarciu kamer, a następnie wciśnięciu przycisku do ventowania gracz wchodzi do venta, a kamery dalej są otwarte, a po zamknięciu gracz może poruszać się niewidzialny

**Comment by thedavesky** [comment]
Naprawione w feature/interaction-point-improvements.
