### ISSUE TITLE
main: tło w menu

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#126]
Obraz w tle w menu głównym może zmienić się na taki sam. Animacja wygląda wtedy dziwnie.

**Comment by qsqus** [comment]
te obrazy w tle są niemal identyczne, czy jesteś pewny?

**Comment by sralikk** [comment]
tak, czasami zdarza się, że obraz zmienia się na taki sam, i wtedy animacja wygląda jakby na ekranie pojawiały się plamy, które po chwili znikają.

**Comment by qsqus** [comment]
naprawione
