### ISSUE TITLE
main: literowka

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#127]
jak na zalaczonym obrazku:

![image](https://github.com/wzimongus/wzimongus/assets/149406418/8fbf76b7-0153-4271-830f-bf30fe319a50)

**Comment by qsqus** [comment]
u mnie nie ma xd
![image](https://github.com/wzimongus/wzimongus/assets/149406771/2e1006e3-4519-4fc8-8f4d-d1598d501a0d)

**Comment by sralikk** [comment]
Właśnie zauważyłem, że literówkę mam tylko jak chce upuścić grę jako uczeń. Jako wykładowca wszystko jest jak powinno.

**Comment by sralikk** [comment]
hmmm, a na fullscreenie masz to samo? Bo jak zacząłem kombinować to okazuje się, że czasami mam dobrze a czasami źle. To znaczy raz jak nie mam fullscreena to mam "tak", a potem jak go włączę to mam "ta", a czasami na odwrót.

**Comment by SGGWAmongUs** [comment]
Niemożliwy do reprodukcji, a kod jest prawidłowy, zamykam
