### ISSUE TITLE
Literówka w minigrze Room Reservation

### ISSUE THREAD

**Issue by KamilMarshal** [wzimongus/wzimongus#128]
W nazwie "Aula III" jest literówka widoczna na poniższym screenie:
![image](https://github.com/wzimongus/wzimongus/assets/108593228/d7b8b1d6-0057-4aab-97b5-418bc8c7bbbb)

**Comment by Valcast** [comment]
![image](https://github.com/wzimongus/wzimongus/assets/50219130/ad6b5e1b-700d-4d92-aa33-9cae897cb072)
![image](https://github.com/wzimongus/wzimongus/assets/50219130/8ea4d8a0-cf34-4ac7-8c5e-541b355e978b)
Nie mam pojęcia czemu to się dzieje, może kwestia czcionki?

Zamieniam na liczby
