### ISSUE TITLE
main: możliwość oblewania przed rozpoczęciem rozgrywki

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#129]
W trakcie ładowania gry, podczas ekranu gdzie zostają przydzielane role, wykładowca może użyć przycisku oblewania ("q"), co pozwala na oblanie ucznia znajdującego się najbliżej wykładowcy już przed startem gry lub od razu po jej rozpoczęciu. Cooldown na zabijanie zaczyna się dopiero chwile po rozpoczęciu gry.

**Comment by qsqus** [comment]
naprawione w bugfixie
