### ISSUE TITLE
main: oblewanie w trakcie zebrania i po nim

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#136]
Gdy zostanie wywołane spotkanie, a wykładowca znajduje się akurat obok jakiegoś ucznia, to jest on w stanie kliknąć przycisk oblewania ("q") podczas tego głosowania i w ten sposób oblać tego ucznia. Po takim oblaniu na mapie nie pojawia się ciało. Oprócz tego, po oblaniu w trakcie głosowania, gdy głosowanie się zakończy, wykładowca może niemal od razu zacząć oblewanie innych. Cooldown jest widoczny, natomiast z jakiegoś powodu i tak można wtedy oblewać:

![image](https://github.com/wzimongus/wzimongus/assets/149406418/0b8c8854-717b-41bb-a934-0c2c18a534d4)

Jak wywołać: 
1. Stwórz grę z przynajmniej 4 graczami (Przy mniejszej ilości rozgrywka od razu po oblaniu się zakończy)
2. Pozostaw obok siebie impostora i ucznia, a za pomocą trzeciego gracza użyj przycisku
3. Podczas głosowania, na ekranie impostora wciśnij q (Efekt oblania będzie widoczny po zakończeniu głosowania)
4. Po głosowaniu jedna osoba jest oblana, a wykładowca może od razu zacząć oblewanie innych pomimo cooldownu

**Comment by thedavesky** [comment]
Naprawione w feature/interaction-point-improvements razem z #121.
