### ISSUE TITLE
main: lobby settings się psuje jak jest komunikat

### ISSUE THREAD

**Issue by qsqus** [wzimongus/wzimongus#141]
![image](https://github.com/wzimongus/wzimongus/assets/149406771/3b256412-6734-4d0d-b171-d82c66a76acf)
![image](https://github.com/wzimongus/wzimongus/assets/149406771/ee79de68-b7fb-49fd-b0be-42954a8effe9)

**Comment by KamilMarshal** [comment]
Fixed in 7c874a5
