### ISSUE TITLE
main: niedziałające taski

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#165]
Po wejściu w taski fill formula i reactor memory crashuje gre. Najprawdopodobniej jest to związane z okienkami tych minigier.

![image](https://github.com/wzimongus/wzimongus/assets/149406418/f3f1ad3c-0808-429d-9a8d-c8ec248385ed)

**Comment by B28Rhein** [comment]
Fixed by Papaj48 in commit 05db061 "Minigame Hotfix"
