### ISSUE TITLE
main: kamery i vent

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#167]
Gdy impostor jest w kamerach i stoi odpowiednio blisko venta, to może do niego wejść poprzez wciśnięcie binda ventowania. Jeżeli gracz nie zrobi nic więcej i wyjdzie z kamer, to po wyjściu z venta na mapie będą oświetlone te pomieszczenia, które są oświetlone na kamerach (1) . Jeżeli natomiast gracz wejdzie w venta w trakcie przeglądania kamer i wyjdzie z niego (wciskając bind ventowania), to po wyjściu z kamer gracz jest zablokowany w miejscu venta - nie może się ruszać i żadne interakcje nie działają (nie może skorzystać z venta, oblać gracza, wykonać sabotażu itd.) (2)

(1)

![image](https://github.com/wzimongus/wzimongus/assets/149406418/ea1117b1-5dc4-461e-941c-ead7100a2e71)

(2)

![image](https://github.com/wzimongus/wzimongus/assets/149406418/1c5e4b91-6296-452e-9c2a-71b5dd9a0eb6)

**Comment by SGGWAmongUs** [comment]
Naprawione w dc487f0
