### ISSUE TITLE
main: kamery

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#168]
Gracz może się poruszać podczas przeglądania kamer + gdy się z nich wyjdzie po przemieszczeniu się to oświetlone dla tego gracza są pomieszczenia, które są na kamerkach.  Gdy po zrobieniu tego wróci się do kamer, to pomieszczenia na nich nie są w ogóle oświetlone (1).

(tym ziutkiem ze screenshota właśnie przeglądam kamerki)

![image](https://github.com/wzimongus/wzimongus/assets/149406418/2ea3e664-c8ab-49c3-8b96-cccef1fbed15)

(1)

![image](https://github.com/wzimongus/wzimongus/assets/149406418/2c5bd0a9-a8c8-485c-8ee4-701f181ad409)

**Comment by SGGWAmongUs** [comment]
Naprawione w dc487f0
