### ISSUE TITLE
Brak wyrzucenia po głosowaniu

### ISSUE THREAD

**Issue by Papaj48** [wzimongus/wzimongus#169]
Osoba przegłosowana nie zalicza gleby, moze sobie dalej biegać, pls naprawcie :ccc

**Comment by Valcast** [comment]
nie zalicza bo jest zakomentowane kill_player, szybkie do poprawienia

**Comment by thedavesky** [comment]
@Valcast czemu zakomentowales i zostało to zmergeowane do maina?

**Comment by Valcast** [comment]
> @Valcast czemu zakomentowales i zostało to zmergeowane do maina?

Umm actually to nie ja, zorientowałem się dopiero wczoraj jak przeglądałem z nudów kod
