### ISSUE TITLE
Main/Ruszanie się podczas minigier

### ISSUE THREAD

**Issue by tomiNiewiadomski** [wzimongus/wzimongus#172]
Podobny problem co jest juz issue z kamerami, podczas minigier gracz sie normalnie porusza, poczas wpisywania haseł zmienia położenie jeśli w haśle jest WASD

![image](https://github.com/wzimongus/wzimongus/assets/149410768/67306db0-e729-4bc2-a308-65d13ea5dd2f)
![image](https://github.com/wzimongus/wzimongus/assets/149410768/33b14476-d523-46cb-828d-7aa19c3bf547)

![image](https://github.com/wzimongus/wzimongus/assets/149410768/f97e2b61-a7a9-483f-bf66-c81d3c09d895)

**Comment by SGGWAmongUs** [comment]
Naprawione w dc487f0
