### ISSUE TITLE
main: po wejściu z jednego aktywnego taska na drugi nie da się go aktywować

### ISSUE THREAD

**Issue by alkaver** [wzimongus/wzimongus#178]
![image](https://github.com/wzimongus/wzimongus/assets/107754123/405fe041-b94b-4025-a256-b14677147ecc)
Po rozmieszaniu tasków na mapie obstawiam, że pewnie nie będą obok siebie, ale i tak zgłaszam

**Comment by SGGWAmongUs** [comment]
To nie problem, taski będą dalej od siebie
