### ISSUE TITLE
main: zabijanie - efekt wizualny

### ISSUE THREAD

**Issue by qsqus** [wzimongus/wzimongus#206]
nie wiem co to powoduje, ale czasami nie widać podświetlenia ofiary i nie widać podświetlenia przycisku, jednak można dalej zabijać naciskając "q"

![image](https://github.com/wzimongus/wzimongus/assets/149406771/03592073-f720-4742-8db2-853e8ea19891)

**Comment by thedavesky** [comment]
Nie można zreprodukować.
