### ISSUE TITLE
main: problem wielu impostorów

### ISSUE THREAD

**Issue by qsqus** [wzimongus/wzimongus#225]
gdy jest więcej niż jeden impostor to można instancjonować ciała z ducha, dzieje się tak tylko dla jednego z dwóch impostorów

- przed instancjonowaniem kolejnego ciała:
![image](https://github.com/wzimongus/wzimongus/assets/149406771/803284b8-46e5-44cf-ac01-fc24ae0f688b)

- po instancjonowaniu kolejnego ciała, widać też, że tylko jeden impostor może instancjonować:
![image](https://github.com/wzimongus/wzimongus/assets/149406771/55d3b18e-7ec3-4f15-8ce3-af035120e82f)

**Comment by KamilMarshal** [comment]
no idea

- oblanie gracza poprawnie zmienia jego status na is_dead
- nie jest możliwe oblanie martwej osoby

Wymyśliłem, że obejdę to dodając dodatkowy warunek sprawdzający czy możliwa ofiara ma collision_layer ustawione na "players". Duch ma zmienione, więc już nie powinno przejść.

Jak odpalić więcej niż 4 instancje, albo wymusić utworzenie 2 impostorów na 4 instancjach?

**Comment by qsqus** [comment]
ja to wymusiłem w kodzie w game_manger.gd

![image](https://github.com/wzimongus/wzimongus/assets/149406771/5310c01f-9621-474a-9680-24db8e673b52)

**Comment by thedavesky** [comment]
Uruchamiając Godota z CLI można uruchomić dowolną ilość instancji (testowałem dzisiaj 10 instancji). Również posiada on tam wiele innych przydatnych argumentów których nie widziałem w GUI.

**Comment by qsqus** [comment]
<div>impostor zabija impostora 💀</div>
<img src='https://github.com/wzimongus/wzimongus/assets/149406771/44f856e9-5a20-44bd-92ac-3a0371e26b68' width='400'>
<img src='https://github.com/wzimongus/wzimongus/assets/149406771/029b3974-0d7e-4b65-a35c-de87ef6e7e26' width='400'>
