### ISSUE TITLE
main: kamery

### ISSUE THREAD

**Issue by qsqus** [wzimongus/wzimongus#229]
cały czas brakuje podświetlenia na kamerach

![image](https://github.com/wzimongus/wzimongus/assets/149406771/2623f5a8-236b-44cb-a159-75ff9e01da6c)

**Comment by qsqus** [comment]
brzydko jest teraz :(

![image](https://github.com/wzimongus/wzimongus/assets/149406771/380b3c02-5957-4d59-8078-10209177c8ba)

**Comment by SGGWAmongUs** [comment]
dodaj grubość outline

**Comment by qsqus** [comment]
dodałem
