### ISSUE TITLE
main: Błędny message przy wyrzuceniu impostora

### ISSUE THREAD

**Issue by KamilMarshal** [wzimongus/wzimongus#240]
Gdy w głosowaniu wyrzucimy ostatniego (jedynego) impostora pojawia się napis, iż nikogo nie wyrzucono:
![image](https://github.com/wzimongus/wzimongus/assets/108593228/4f9dffd5-ace3-4758-a0f9-cf023ff3568c)
a następnie okno wygranej studentów:
![image](https://github.com/wzimongus/wzimongus/assets/108593228/f5a156a5-d23f-433d-ad12-0b7b6b4732ca)

**Comment by Valcast** [comment]
Mógłbyś opisać krok po kroku jak dojść do tego błędu, testowałem właśnie dla 3 graczy i wyrzucałem impostora, pisało, że był wykładowcą

**Comment by SGGWAmongUs** [comment]
Błąd niereprodukowalny
