### ISSUE TITLE
main: animacja wyrzucenia

### ISSUE THREAD

**Issue by qsqus** [wzimongus/wzimongus#248]
gdy nikt nie zostanie wyrzucony to spada sam parasol + animacja jest przed napisem

![image](https://github.com/wzimongus/wzimongus/assets/149406771/b44908db-c491-4fd0-bf91-55f1f04c9d43)

**Comment by SGGWAmongUs** [comment]
ten efekt jest zamierzony (uważałem że wygląda śmiesznie)
