### ISSUE TITLE
main: impostor może zabić przez ścianę

### ISSUE THREAD

**Issue by qsqus** [wzimongus/wzimongus#252]
gdy ustawi się większy promień oblania, to nie dość, że gracz podświetla się po drugiej stronie ściany, to impostor też może go zabić

![image](https://github.com/wzimongus/wzimongus/assets/149406771/c14c088e-d7a1-494a-b4bb-2bf541bf1daa)

**Comment by SGGWAmongUs** [comment]
naprawione :)
