### ISSUE TITLE
feature\voting-screen: Problemy z minigrami

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#64]
1. Gdy gracz jest w trakcie minigry i zostanie rozpoczęte głosowanie, to po zakończonym głosowaniu gracz jest w stanie poruszać się w trakcie dokańczania minigry po głosowaniu. Oprócz tego, jeżeli gracz skończy taska poza miejscem, w którym znajduje się minigra to wywala gre.

2. Gdy gracz jest w trakcie minigry i zostanie rozpoczęte głosowanie, to podczas tego głosowania gracz może wyjść z minigry poprzez wciśnięcie krzyżyka w prawym górnym rogu. Po zrobieniu tego gracz jest w stanie poruszać się po mapie w trakcie głosowania.

**Comment by qsqus** [comment]
naprawione w feature/report
