### ISSUE TITLE
feature/menu-settings: Reset rozdzielczości po przeniesieniu okna gry na drugi monitor mający inną rozdzielczość

### ISSUE THREAD

**Issue by thedavesky** [wzimongus/wzimongus#65]
1. Ustaw na pierwszym monitorze w grze rozdzielczość nieobsługiwaną przez drugi monitor.
2. Przenieś okno z grą na drugi monitor.
3. Wejdź do gry.
4. Rozdzielczość zostaje ustawiona na 800x600, a okno cofa się na pierwszy monitor.

<img width="2180" alt="Screenshot 2023-12-27 at 22 18 00" src="https://github.com/wzimongus/wzimongus/assets/48188892/b76d0706-8413-4630-9fbf-de71379019ea">
<img width="2180" alt="Screenshot 2023-12-27 at 22 18 20" src="https://github.com/wzimongus/wzimongus/assets/48188892/d22d2545-a58c-4d3e-a67d-7664fb1db7eb">
<img width="2180" alt="Screenshot 2023-12-27 at 22 18 35" src="https://github.com/wzimongus/wzimongus/assets/48188892/03cd429d-15d2-4702-984d-f4f5ebcd119e">

**Comment by qsqus** [comment]
"naprawione" w feature/settings-improvements2
