### ISSUE TITLE
Możliwość odpalenia kamer podczas ventowania po prawej stronie mapy

### ISSUE THREAD

**Issue by Papaj48** [wzimongus/wzimongus#85]
W momencie ventowania w stronę prawego skrajnego venta, mozna w pewnym momencie odpalić kamery i przeglądać kamery z venta. Po odpaleniu i wyłączeniu kamer w vencie można poruszać się strzałkami pod mapą

**Comment by qsqus** [comment]
naprawione w feature/ui
