### ISSUE TITLE
main : nie działa 

### ISSUE THREAD

**Issue by alkaver** [wzimongus/wzimongus#90]
![image](https://github.com/wzimongus/wzimongus/assets/107754123/dc5538c5-c1f0-4aab-8eb7-f3c567075c05)
Sklonowałem od nowa repozytorium i nie działa main?

**Comment by thedavesky** [comment]
Został zmieniony system ustawień, co powoduje, że obecnie zapisane ustawienia są nieprawidłowe.
Należy wyczyścić obecne ustawienia poprzez usunięcie danych gry w danym folderze zależnie od systemu:
Windows: %APPDATA%\Godot\app_userdata\[nazwa_gry]
macOS: ~/Library/Application Support/Godot/app_userdata/[nazwa_gry]
Linux: ~/.local/share/godot/app_userdata/[nazwa_gry]
