### ISSUE TITLE
main: problem z ventami i kamerami

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#92]
Przemieszczając się między ventami, które znajdują się w prawym dolnym rogu mapy przez chwilę mamy możliwość wciśnięcia przycisku interakcji (bo obok górnego venta znajdują się kamery). Gdy będziemy spamować przycisk interakcji w trakcie przemieszczania się między ventami to jesteśmy w stanie włączyć kamery będąc w vencie. Gdy po tym gracz wyłączy kamery, to jest w stanie poruszać się po całej mapie będąc niewidocznym.

Odpalenie kamer w innym miejscu na mapie:
![image](https://github.com/wzimongus/wzimongus/assets/149406418/da633112-011f-4ce9-ab20-f155a5b8f615)

Przemieszczanie się po mapie będąc niewidzialnym:
![image](https://github.com/wzimongus/wzimongus/assets/149406418/31ec47d4-6b01-426e-9885-caae4ce93255)

**Comment by SGGWAmongUs** [comment]
Naprawione na `main`
