### ISSUE TITLE
feature/report: nie można głosować po zgłoszeniu ciała ani po wezwaniu zebrania

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#95]
Po zgłoszeniu ciała i po wezwaniu zebrania odpala się ekran głosowania, lecz nie pojawiają się w nim gracze i nie można na nikogo zagłosować. Można jedynie pominąć głos.

![image](https://github.com/wzimongus/wzimongus/assets/149406418/3b37e830-a498-45dc-9d55-1f9f180ef005)

**Comment by qsqus** [comment]
naprawiłem, to była wina czatu
