### ISSUE TITLE
feature/skins: ecoswir i hipster

### ISSUE THREAD

**Issue by sralikk** [wzimongus/wzimongus#96]
(Pod postaciami)

![ecoswir](https://github.com/wzimongus/wzimongus/assets/149406418/0dd8e712-be18-498e-aa51-9ac03d7185cf)

![hipster](https://github.com/wzimongus/wzimongus/assets/149406418/93011f7c-37bd-435e-ad81-68f84da24faa)

**Comment by KamilMarshal** [comment]
Fixed #100
